//Każdy wyjątek i błąd leci do  sentry.io

throw new \Exception('Bad stuff happend'); 
